version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run: apt-get update && apt-get install -y cmake g++
      - run: mkdir -p build
      - run: cd build && cmake ..
      - run: cd build && make